[package]
name = "hkt-pin-list"
description = "Self managed HKT intrusive linked list"
version = "0.3.1"
edition = "2021"
authors = ["storycraft <storycraft@pancake.sh>"]
license = "MIT"
repository = "https://github.com/storycraft/hkt-pin-list"

[dependencies]
pin-project-lite = "0.2"
paste = "1"